apiVersion: apps/v1
kind: Deployment

metadata:
  name: nick-portfolio

spec:
  replicas: 3

  selector:
    matchLabels:
      app: nick-portfolio

  template:
    metadata:
      labels:
        app: nick-portfolio

    spec:
      containers:
      - name: nick-portfolio
        image: nick-vs-docker-app:v3
        ports:
        - containerPort: 5000



        